server:
  port: 8087 # Chạy analytics-service trên cổng mới

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/analytics_service_db?useSSL=false&characterEncoding=utf8&useUnicode=true&serverTimezone=UTC
    username: root # Thay bằng username của bạn
    password: huynhdat123@ # Thay bằng mật khẩu của bạn
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
