# ===============================================================
# FILE: api-gateway.yml (Phiên bản đã sửa lỗi routing và filter)
# LOCATION: config-repo/api-gateway.yml
# ===============================================================

server:
  port: 8080 # Cổng Gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    hostname: api-gateway

spring:
  # Codec configuration for large file uploads (Gateway uses reactive, not servlet)
  codec:
    max-in-memory-size: 10MB
  
  cloud:
    gateway:
      # [COMMAND]: TẮT discovery locator
      discovery:
        locator:
          enabled: false
      
      # HTTP client configuration for large file uploads
      httpclient:
        connect-timeout: 45000
        response-timeout: 60s

      # [COMMAND]: Các route tường minh
      routes:
        # --- Route cho Auth Service (KHÔNG cần filter) ---
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/** # Cho phép login, validate

        # --- Các route cần bảo vệ ---
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            # XÓA BỎ "- StripPrefix=1"
            - AuthenticationFilter # <-- ÁP DỤNG FILTER XÁC THỰC

        - id: packages-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/packages/**
          filters:
            - AuthenticationFilter # <-- ÁP DỤNG FILTER XÁC THỰC

        - id: station-service-routes
          uri: lb://STATION-SERVICE
          predicates:
            - Path=/api/stations/**, /api/chargers/**, /api/incidents/**
          filters:
            # XÓA BỎ "- StripPrefix=1"
            - AuthenticationFilter # <-- ÁP DỤNG FILTER XÁC THỰC

        - id: maintenance-service-route
          uri: lb://STATION-SERVICE
          predicates:
            - Path=/api/maintenance/**
          filters:
            - AuthenticationFilter # <-- ÁP DỤNG FILTER XÁC THỰC

        - id: charging-service-route
          uri: lb://CHARGING-SERVICE
          predicates:
            - Path=/api/sessions/**
          filters:
            # XÓA BỎ "- StripPrefix=1"
            - AuthenticationFilter # <-- ÁP DỤNG FILTER XÁC THỰC

        - id: transactions-service-route
          uri: lb://CHARGING-SERVICE
          predicates:
            - Path=/api/transactions/**
          filters:
            - AuthenticationFilter # <-- ÁP DỤNG FILTER XÁC THỰC

        - id: reservations-service-route
          uri: lb://CHARGING-SERVICE
          predicates:
            - Path=/api/reservations/**
          filters:
            - AuthenticationFilter # <-- ÁP DỤNG FILTER XÁC THỰC

        - id: payment-service-routes
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**, /api/wallet/**, /api/wallets/**
          filters:
            # XÓA BỎ "- StripPrefix=1"
            - AuthenticationFilter # <-- ÁP DỤNG FILTER XÁC THỰC

        - id: notification-service-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**
          filters:
            # XÓA BỎ "- StripPrefix=1"
            - AuthenticationFilter # <-- ÁP DỤNG FILTER XÁC THỰC

        - id: fcm-tokens-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/fcm-tokens/**
          filters:
            - AuthenticationFilter # <-- ÁP DỤNG FILTER XÁC THỰC

        - id: loyalty-service-route
          uri: lb://LOYALTY-SERVICE
          predicates:
            - Path=/api/loyalty/**
          filters:
            - AuthenticationFilter # <-- ÁP DỤNG FILTER XÁC THỰC

      # [COMMAND]: XÓA BỎ HOẶC COMMENT LẠI globalcors
      # globalcors:
      #   corsConfigurations:
      #     '[/**]':
      #       allowedOrigins: "*"
      #       allowedMethods:
      #         - GET
      #         - POST
      #         - PUT
      #         - DELETE
      #         - OPTIONS
      #       allowedHeaders: "*"

      # Load Balancer - Disable cache temporarily to avoid stale entries
      loadbalancer:
        cache:
          enabled: false  # Disable cache to ensure fresh service resolution
        # Use Eureka for service discovery
        use-404: false

# Logging (Giữ nguyên)
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    # com.netflix.discovery: INFO # Có thể giảm bớt log Eureka nếu muốn
    # org.springframework.web: INFO

# Actuator (Giữ nguyên)
management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info,routes,refresh
  endpoint:
    gateway:
      enabled: true