# FILE: auth-service.yml (trong thư mục config-repo)

server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service_db?useSSL=false&characterEncoding=utf8&useUnicode=true&serverTimezone=UTC
    username: root
    password: huynhdat123@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false
    hostname: auth-service
    non-secure-port: 8086

# --- Cấu hình JWT ---
jwt:
  secret: f4f54e19a4e3b5e1b2e6a3d7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7
  expirationMs: 86400000