server:
  port: 8082 # Chạy charging-service trên cổng mới

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/charging_service_db?useSSL=false&characterEncoding=utf8&useUnicode=true&serverTimezone=UTC
    username: root # Thay bằng username của bạn
    password: huynhdat123@ # Thay bằng mật khẩu của bạn
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost # Địa chỉ RabbitMQ broker (đang chạy trên Docker)
    port: 5672     # Cổng AMQP mặc định
    username: guest  # Username mặc định
    password: guest  # Password mặc định
app:
  rabbitmq:
    exchange: charging_events

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false
    hostname: charging-service
    non-secure-port: 8082