server:
  port: 8083 # Chạy payment-service trên cổng mới

spring:
  application:
    name: PAYMENT-SERVICE  # Phải khớp với tên trong FeignClient và API Gateway route
  datasource:
    url: jdbc:mysql://localhost:3306/payment_service_db?useSSL=false&characterEncoding=utf8&useUnicode=true&serverTimezone=UTC
    username: root # Thay bằng username của bạn
    password: huynhdat123@ # Thay bằng mật khẩu của bạn
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false
    hostname: payment-service
    non-secure-port: 8083
    instance-id: ${spring.application.name}:${server.port}

# App-specific configuration
app:
  rabbitmq:
    queue: payment.success

# Logging
logging:
  level:
    com.paymentservice: DEBUG
    org.springframework.amqp: DEBUG