# FILE: user-service.yml (đặt trong thư mục config-repo)
server:
  port: 9000 # Cổng mà user-service sẽ chạy

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db?useSSL=false&characterEncoding=utf8&useUnicode=true&serverTimezone=UTC
    username: root # Thay bằng username của bạn
    password: huynhdat123@ # Thay bằng mật khẩu của bạn
  jpa:
    hibernate:
      ddl-auto: update # Tự động cập nhật schema, hữu ích khi phát triển
    show-sql: true # Hiển thị câu lệnh SQL trong console

  # Multipart upload configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

# Cloudinary Configuration for Avatar Upload
cloudinary:
  enabled: true
  cloud-name: dksgckopr
  api-key: 149974635413495
  api-secret: svNqRGPmlp0Ak6y72hrIVB3p4yk

# Cấu hình để user-service đăng ký với eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/